// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDruhTI2rLw9fkvUPEH5WX-lArZ5zh-YUs',
    appId: '1:839058303823:android:fa2c98402062ea1220f33a',
    messagingSenderId: '839058303823',
    projectId: 'student-attendence-erp',
    storageBucket: 'student-attendence-erp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA33G3K9hm_kbGhwS2RgoNHRo7QnFtB5ls',
    appId: '1:839058303823:ios:6d92087bc22b554b20f33a',
    messagingSenderId: '839058303823',
    projectId: 'student-attendence-erp',
    storageBucket: 'student-attendence-erp.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalExamPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXPBHRsdVMx3lPj1BbMd66g_ECZR8QlWg',
    appId: '1:839058303823:web:bcb8390e068aebda20f33a',
    messagingSenderId: '839058303823',
    projectId: 'student-attendence-erp',
    authDomain: 'student-attendence-erp.firebaseapp.com',
    storageBucket: 'student-attendence-erp.firebasestorage.app',
  );
}
